name: 'manual: pantavisor-bsp'

on:
  workflow_dispatch:

jobs:

  build-raspberrypi-armv8-scarthgap:
    uses: ./.github/workflows/build-pantavisor-bsp.yaml
    with:
      # meta-pantavisor
      configs: .github/configs/shared-vols.yaml:.github/configs/release/raspberrypi-armv8-scarthgap.yaml
      name: raspberrypi-armv8
